#line 2 "lex_yy.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>


#if !defined(_WIN32)
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
static yyconst short int yy_accept[419] =
    {   0,
       75,   75,   75,   75,   75,   75,   80,   78,   75,   79,
       78,   78,   78,   78,   55,   53,   78,   78,   78,   49,
       49,   49,   78,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       75,   78,   77,   78,   55,   53,   76,   78,   55,   53,
       49,   75,    0,   56,    0,    0,    0,   55,   53,   74,
        0,   55,    0,    0,    0,   53,   48,   46,   47,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   41,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   75,
        0,    0,   71,    0,    0,    0,    0,    0,   55,   53,
       51,   55,    0,   53,   55,   53,    0,   55,    0,   53,
       49,   56,   57,    0,   57,    0,    0,   73,    0,   52,
       54,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   42,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,    0,    0,    0,    0,    0,    0,   51,    0,
       51,   50,   49,   59,   58,    0,   52,   49,   38,   49,

       49,   49,   18,   25,   49,   49,   49,   49,   49,   12,
       49,   49,   49,   49,   49,   49,   22,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   29,   49,   49,    0,
        0,    0,    0,    0,    0,   51,   45,   58,    0,   39,
       49,   49,   49,    9,   49,   49,   49,   49,   49,   49,
       20,   40,   49,    7,   49,   28,   49,   49,   49,   49,
       49,   49,   49,   23,   49,   49,   49,   49,   49,   49,
       16,   49,   49,   26,   49,   70,    0,    0,    0,    0,
       49,   49,   49,   49,   30,   49,   21,   49,   49,   49,

        1,   43,   44,   49,   34,    2,   49,   49,   13,   11,
       49,   17,   49,   49,   49,   49,   49,   68,    0,    0,
        0,    0,    0,    0,   49,   49,   27,    6,   19,   49,
       36,   49,   35,   49,   49,   49,   49,   10,   49,   49,
       14,   69,    0,    0,   72,    0,    0,   67,    0,    0,
       66,   37,   49,   49,   49,    3,   15,   33,   49,   24,
       49,    0,    0,    0,    0,    0,    0,    4,    5,    8,
       49,   31,   63,    0,    0,    0,   49,    0,    0,    0,
       32,    0,    0,    0,    0,    0,    0,    0,   64,    0,
        0,   65,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   60,    0,    0,    0,
        0,    0,    0,    0,    0,   61,   62,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    8,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   16,   17,    1,   18,
        1,   19,    1,    1,   20,   21,   21,   22,   23,   24,
       25,   25,   26,   25,   25,   27,   25,   25,   25,   25,
       25,   28,   29,   30,   31,   25,   25,   32,   25,   25,
        1,   33,    1,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   25,   25,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   25,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    1,    1,    1,    4,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    6,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[429] =
    {   0,
        0,   56,   56,   71,   77,  116,  732,  733,   60,  733,
       62,  698,   82,   66,   90,   85,  713,  711,  709,    0,
      707,  698,    0,   58,  678,   67,   30,   69,   46,  678,
      676,  675,   89,   83,   68,   99,   90,  675,   81,   97,
      153,  159,  733,  129,  153,  165,  733,  156,  182,  196,
      143,  211,   78,  733,  106,  712,  175,  208,  211,  733,
      716,  214,  228,  244,    0,  247,  733,  733,  733,    0,
      691,  686,    0,  665,  663,  667,  662,  677,  665,  659,
      669,  655,  654,  669,  668,  657,  139,  113,  665,  650,
      662,  665,  647,  655,  661,  653,  660,  645,  646,  642,

      643,  647,  636,  640,  190,  643,  643,  643,  632,  264,
      234,    0,  733,  677,  269,  644,  638,  630,  264,  276,
      307,  286,  296,  325,  338,  343,  185,  353,  372,  384,
      632,  212,  733,  670,  669,  299,  673,  733,  279,  388,
        0,  646,  651,  621,  622,  627,  631,  619,  197,  616,
      632,  630,  620,  625,  611,  627,  608,  621,  624,  617,
      604,  617,  600,  605,    0,  599,  608,  600,  612,  596,
      598,  110,  599,  594,  599,  605,  596,  599,  588,  602,
      604,  588,  324,  631,  630,  596,  588,  598,    0,  364,
      733,  290,  587,  733,  733,  328,  733,  608,    0,  580,

      586,  589,    0,    0,  575,  587,  578,  571,  579,    0,
      574,  574,  568,  567,  568,  573,    0,  572,  563,  579,
      560,  577,  568,  571,  562,  569,  555,  560,  568,  557,
      566,  565,  563,  554,  558,  559,    0,  547,  553,  589,
      179,  548,  554,  551,  302,  394,    0,  733,  583,    0,
      555,  553,  553,    0,  531,  541,  541,  545,  531,  532,
        0,    0,  541,    0,  541,    0,  522,  539,  495,  498,
      475,  478,  477,    0,  481,  468,  468,  475,  481,  476,
        0,  468,  461,    0,  466,  733,  411,  459,  415,  464,
      470,  453,  459,  452,    0,  451,    0,  459,  444,  465,

        0,    0,    0,  459,    0,    0,  452,  458,    0,    0,
      442,    0,  441,  452,  452,  433,  448,  733,  421,  436,
      485,  440,  444,  452,  434,  430,    0,    0,    0,  430,
        0,  432,    0,  406,  423,  410,  422,    0,  410,  399,
        0,  733,  450,  441,  733,  437,  465,  733,  469,  430,
      471,    0,  383,  373,  374,    0,    0,    0,  370,    0,
      366,  398,  473,  375,  345,  341,  351,    0,    0,    0,
      345,    0,  733,  337,  344,  331,  334,  330,  323,  311,
        0,  321,  313,  306,  299,  288,  291,  299,  733,  286,
      222,  733,  277,  281,  267,  260,  243,  237,  240,  222,

      239,  218,  169,  213,  202,  193,  733,  174,  145,  127,
       95,   43,   44,   14,   10,  733,  733,  733,  527,  533,
      537,  540,  545,  551,  555,  559,  565,  571
    } ;

static yyconst short int yy_def[429] =
    {   0,
      418,    1,    1,    1,    1,    1,  418,  418,  418,  418,
      419,  420,  418,  418,  418,  418,  418,  418,  418,  421,
      421,  421,  422,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      421,  418,  419,  418,  419,  418,  423,  418,  418,  418,
      424,  418,  418,  418,  425,  418,  418,  418,  418,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  418,
      418,   42,  418,   42,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      421,  419,  418,  418,  418,  418,  424,  418,  418,  418,
      425,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  418,  426,  418,  418,  418,  418,  121,  418,
      418,  418,  421,  418,  418,  418,  418,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  426,
      418,  418,  418,  418,  418,  418,  421,  418,  418,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  418,  418,  418,  418,  418,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  418,  418,  418,
      427,  428,  418,  418,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  418,  418,  427,  418,  428,  428,  418,  428,  428,
      418,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  428,  418,  418,  418,  418,  418,  421,  421,  421,
      421,  421,  418,  418,  418,  418,  421,  418,  418,  418,
      421,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,    0,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418
    } ;

static yyconst short int yy_nxt[791] =
    {   0,
        8,    9,   10,    9,    9,   11,    8,   12,    8,    8,
       13,    8,   14,   15,   16,   16,   17,   18,   19,   20,
       20,   20,   20,   21,   20,   20,   20,   20,   20,   22,
       20,   20,    8,   23,   24,   25,   26,   27,   28,   29,
       20,   20,   30,   31,   32,   20,   33,   34,   20,   35,
       36,   37,   38,   39,   40,   20,   20,   41,   43,  417,
       41,   52,   42,   52,   52,  416,   44,   54,   81,   45,
       46,   46,   41,   43,   60,   41,   82,   42,   61,   47,
       85,   44,  415,   54,   45,   46,   46,   48,  414,   86,
       49,   50,   50,   74,   55,   58,   59,   59,   66,   66,

       66,   77,   96,   62,   62,   63,   97,   64,   78,   75,
       55,  132,   64,   79,   83,  106,   51,   41,   47,   80,
       41,   65,   42,   64,   84,   90,   48,  107,   64,   49,
       50,   50,   94,  108,   91,   95,   92,   98,   55,  103,
       99,   93,  119,  120,  120,   65,  104,  109,  413,  159,
      100,  101,  228,  102,  110,   51,   52,  110,  160,  111,
      112,  113,  229,  114,  121,  412,  122,  122,  123,  125,
      126,  126,  115,  115,  115,   64,  121,   85,  124,  124,
      124,  286,  135,  287,   65,  157,   86,   64,  136,  136,
      158,   64,  131,  127,  411,  128,  128,  129,  192,  192,

      192,  116,  117,   64,   64,  405,  118,  127,   65,  130,
      130,  130,   52,   65,   52,   52,  410,   54,   64,  406,
       64,   62,   62,   63,   66,   66,   66,   62,   62,   63,
       64,  409,  177,   64,   64,  183,   64,   65,  183,   65,
      178,   63,   63,   63,   55,  408,   64,  205,  206,   64,
       64,  407,   64,  139,  139,  404,  393,  140,  140,  140,
       66,   66,   66,   65,  394,  110,   64,   52,  110,   64,
      111,  113,  403,  185,  402,  121,  401,  122,  122,  123,
      400,  118,  115,  115,  115,   64,   64,  121,  399,  124,
      124,  124,  140,  140,  140,   65,  398,  121,   64,  122,

      122,  123,   64,  192,  192,  192,  195,  121,   64,  123,
      123,  123,  196,  196,   64,  246,  246,  246,   64,   65,
      189,  189,  189,  397,   64,  183,  396,  395,  183,  190,
      191,  392,  391,  191,   64,  248,  121,  390,  124,  124,
      124,  249,  249,  389,  388,  190,  191,   64,  387,  127,
      191,  128,  128,  129,  127,  386,  130,  130,  130,  385,
       64,  384,  383,   64,  127,   64,  128,  128,  129,   65,
      382,  118,  381,  245,  245,   64,   64,  246,  246,  246,
      380,   64,  379,  127,  378,  129,  129,  129,  377,  376,
      375,   64,  374,   65,   64,  127,  373,  130,  130,  130,

      348,  140,  140,  140,  372,  371,   64,  246,  246,  246,
       64,  197,  370,  318,  197,  319,  322,  191,  369,  322,
      191,  368,   64,  342,  320,  320,  320,  197,  323,  323,
      323,  197,  348,  191,  343,  343,  343,  191,  318,  348,
      319,  347,  348,  345,  347,  350,  361,  360,  350,  320,
      320,  320,  342,  349,  349,  349,  359,  323,  323,  323,
      358,  357,  356,  343,  343,  343,  347,  348,  355,  347,
      362,  348,  363,  362,  363,  363,  354,  363,  349,  349,
      349,  353,  349,  349,  349,  352,  351,  345,  341,  340,
      339,  338,  337,  336,  335,  334,  364,  333,  364,  332,

      331,  330,  329,  328,  327,  326,  325,  365,  324,  365,
      321,  317,  316,  315,  314,  313,  312,  311,  366,  310,
      366,  309,  308,  307,  367,  306,  367,   53,   53,   53,
       53,   53,   53,   56,  305,   56,   56,   56,   56,   70,
       70,   70,   70,   73,   73,  134,  304,  134,  134,  134,
      134,  137,  137,  137,  137,  137,  137,  141,  141,  240,
      240,  240,  240,  240,  240,  344,  344,  344,  344,  344,
      344,  346,  346,  346,  346,  346,  346,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      248,  290,  289,  288,  241,  285,  284,  283,  282,  281,

      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  247,  244,  243,  242,  184,  241,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  204,  203,
      202,  201,  200,  199,  198,  138,  194,  194,  193,  188,
      187,  186,  184,  182,  181,  180,  179,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,

      163,  162,  161,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  138,  133,
      105,   89,   88,   87,   76,   72,   71,   69,   68,   67,
       57,  418,    7,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418
    } ;

static yyconst short int yy_chk[791] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    3,  415,
        2,    9,    2,    9,    9,  414,    3,   11,   27,    3,
        3,    3,    4,    4,   14,    4,   27,    4,   14,    5,
       29,    4,  413,   53,    4,    4,    4,    5,  412,   29,
        5,    5,    5,   24,   11,   13,   13,   13,   16,   16,

       16,   26,   35,   15,   15,   15,   35,   16,   26,   24,
       53,   55,   15,   26,   28,   39,    5,    6,    6,   26,
        6,   15,    6,   16,   28,   33,    6,   39,   15,    6,
        6,    6,   34,   40,   33,   34,   33,   36,   55,   37,
       36,   33,   44,   44,   44,   15,   37,   40,  411,   88,
       36,   36,  172,   36,   41,    6,   41,   41,   88,   41,
       42,   42,  172,   42,   45,  410,   45,   45,   45,   48,
       48,   48,   42,   42,   42,   45,   46,   51,   46,   46,
       46,  241,   57,  241,   45,   87,   51,   46,   57,   57,
       87,   45,   51,   49,  409,   49,   49,   49,  127,  127,

      127,   42,   42,   46,   49,  403,   42,   50,   45,   50,
       50,   50,   52,   49,   52,   52,  408,  132,   50,  403,
       49,   58,   58,   58,   59,   59,   59,   62,   62,   62,
       58,  406,  105,   59,   50,  111,   62,   49,  111,   58,
      105,   63,   63,   63,  132,  405,   58,  149,  149,   59,
       63,  404,   62,   64,   64,  402,  391,   64,   64,   64,
       66,   66,   66,   58,  391,  110,   63,  110,  110,   66,
      110,  115,  401,  115,  400,  119,  399,  119,  119,  119,
      398,  111,  115,  115,  115,   66,  119,  120,  397,  120,
      120,  120,  139,  139,  139,  119,  396,  122,  120,  122,

      122,  122,  119,  192,  192,  192,  136,  123,  122,  123,
      123,  123,  136,  136,  120,  245,  245,  245,  123,  119,
      121,  121,  121,  395,  122,  183,  394,  393,  183,  121,
      121,  390,  388,  121,  123,  196,  124,  387,  124,  124,
      124,  196,  196,  386,  385,  121,  121,  124,  384,  125,
      121,  125,  125,  125,  126,  383,  126,  126,  126,  382,
      125,  380,  379,  124,  128,  126,  128,  128,  128,  125,
      378,  183,  377,  190,  190,  128,  125,  190,  190,  190,
      376,  126,  375,  129,  374,  129,  129,  129,  371,  367,
      366,  128,  365,  125,  129,  130,  364,  130,  130,  130,

      362,  140,  140,  140,  361,  359,  130,  246,  246,  246,
      129,  140,  355,  287,  140,  287,  289,  246,  354,  289,
      246,  353,  130,  319,  287,  287,  287,  140,  289,  289,
      289,  140,  350,  246,  319,  319,  319,  246,  320,  346,
      320,  322,  322,  344,  322,  323,  340,  339,  323,  320,
      320,  320,  343,  322,  322,  322,  337,  323,  323,  323,
      336,  335,  334,  343,  343,  343,  347,  347,  332,  347,
      349,  349,  351,  349,  363,  351,  330,  363,  347,  347,
      347,  326,  349,  349,  349,  325,  324,  321,  317,  316,
      315,  314,  313,  311,  308,  307,  351,  304,  363,  300,

      299,  298,  296,  294,  293,  292,  291,  351,  290,  363,
      288,  285,  283,  282,  280,  279,  278,  277,  351,  276,
      363,  275,  273,  272,  351,  271,  363,  419,  419,  419,
      419,  419,  419,  420,  270,  420,  420,  420,  420,  421,
      421,  421,  421,  422,  422,  423,  269,  423,  423,  423,
      423,  424,  424,  424,  424,  424,  424,  425,  425,  426,
      426,  426,  426,  426,  426,  427,  427,  427,  427,  427,
      427,  428,  428,  428,  428,  428,  428,  268,  267,  265,
      263,  260,  259,  258,  257,  256,  255,  253,  252,  251,
      249,  244,  243,  242,  240,  239,  238,  236,  235,  234,

      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  216,  215,  214,  213,
      212,  211,  209,  208,  207,  206,  205,  202,  201,  200,
      198,  193,  188,  187,  186,  185,  184,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  171,  170,  169,
      168,  167,  166,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  148,  147,
      146,  145,  144,  143,  142,  137,  135,  134,  131,  118,
      117,  116,  114,  109,  108,  107,  106,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,

       91,   90,   89,   86,   85,   84,   83,   82,   81,   80,
       79,   78,   77,   76,   75,   74,   72,   71,   61,   56,
       38,   32,   31,   30,   25,   22,   21,   19,   18,   17,
       12,    7,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "idl.ll"
#define INITIAL 0
/*

COPYRIGHT

Copyright 1992, 1993, 1994 Sun Microsystems, Inc.  Printed in the United
States of America.  All Rights Reserved.

This product is protected by copyright and distributed under the following
license restricting its use.

The Interface Definition Language Compiler Front End (CFE) is made
available for your use provided that you include this license and copyright
notice on all media and documentation and the software program in which
this product is incorporated in whole or part. You may copy and extend
functionality (but may not remove functionality) of the Interface
Definition Language CFE without charge, but you are not authorized to
license or distribute it to anyone else except as part of a product or
program developed by you or with the express written consent of Sun
Microsystems, Inc. ("Sun").

The names of Sun Microsystems, Inc. and any of its subsidiaries or
affiliates may not be used in advertising or publicity pertaining to
distribution of Interface Definition Language CFE as permitted herein.

This license is effective until terminated by Sun for failure to comply
with this license.  Upon termination, you shall destroy or return all code
and documentation for the Interface Definition Language CFE.

INTERFACE DEFINITION LANGUAGE CFE IS PROVIDED AS IS WITH NO WARRANTIES OF
ANY KIND INCLUDING THE WARRANTIES OF DESIGN, MERCHANTIBILITY AND FITNESS
FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, OR ARISING FROM A COURSE OF
DEALING, USAGE OR TRADE PRACTICE.

INTERFACE DEFINITION LANGUAGE CFE IS PROVIDED WITH NO SUPPORT AND WITHOUT
ANY OBLIGATION ON THE PART OF Sun OR ANY OF ITS SUBSIDIARIES OR AFFILIATES
TO ASSIST IN ITS USE, CORRECTION, MODIFICATION OR ENHANCEMENT.

SUN OR ANY OF ITS SUBSIDIARIES OR AFFILIATES SHALL HAVE NO LIABILITY WITH
RESPECT TO THE INFRINGEMENT OF COPYRIGHTS, TRADE SECRETS OR ANY PATENTS BY
INTERFACE DEFINITION LANGUAGE CFE OR ANY PART THEREOF.

IN NO EVENT WILL SUN OR ANY OF ITS SUBSIDIARIES OR AFFILIATES BE LIABLE FOR
ANY LOST REVENUE OR PROFITS OR OTHER SPECIAL, INDIRECT AND CONSEQUENTIAL
DAMAGES, EVEN IF SUN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

Use, duplication, or disclosure by the government is subject to
restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in
Technical Data and Computer Software clause at DFARS 252.227-7013 and FAR
52.227-19.

Sun, Sun Microsystems and the Sun logo are trademarks or registered
trademarks of Sun Microsystems, Inc.

SunSoft, Inc.  
2550 Garcia Avenue 
Mountain View, California  94043

NOTE:

SunOS, SunSoft, Sun, Solaris, Sun Microsystems or the Sun logo are
trademarks or registered trademarks of Sun Microsystems, Inc.

 */
/*
 * idl.ll - Lexical scanner for IDL 1.1
 */
#line 70 "idl.ll"
#include "os_stdlib.h"
#include "os_heap.h"
#include "idl.h"
#include "idl_extern.h"
#include "utl_incl.h"

#include "fe_private.h"

#ifdef VERSION
#undef VERSION
#endif

#include "y_tab.h"
#include <string.h>

#include "preprocess.h"

#undef input
#define input() ((yytchar=yysptr>yysbuf?U(*--yysptr):preprocess_getc())==10?(yylineno++,yytchar):yytchar)

#define YY_INPUT(buf,result,max_size) \
    { \
    int c = preprocess_getc(); \
    result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
    }

static char	idl_escape_reader(char *);
static double	idl_atof(char *);
static long	idl_atoi(char *, long);
static void	idl_parse_line_and_file(char *);

#ifdef __cplusplus
extern "C" int fstackdepth;
#else
extern int fstackdepth;
#endif

// HPUX has yytext typed to unsigned char *. We make sure here that
// we'll always use char *
#define CPPGEN_YYTEXT ((char *)yytext)

#define NORMAL_STATE 1
#define PRAGMA_STATE 2

#line 116 "idl.ll"
	/* This lets us get exclusive states */
	static int first_time = 1;
/* This tells flex to read only one input file */
/* This removes the need to wrap unistd.h in a preprocessor if block, but the
   version of flex we use does not support it. Should we upgrade to a newer
   version, please uncomment this option to remove the need for the
   lex_yy.cpp.patch file. */
/* %option nounistd */
#line 799 "lex_yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 128 "idl.ll"



	if(first_time)
	{
		/* ensures that we start off in the NORMAL state */
		BEGIN NORMAL_STATE;
		first_time = 0;
	}



#line 966 "lex_yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 419 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 733 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 140 "idl.ll"
return MODULE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 141 "idl.ll"
return RAISES;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 142 "idl.ll"
return READONLY;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "idl.ll"
return ATTRIBUTE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 144 "idl.ll"
return EXCEPTION;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 145 "idl.ll"
return CONTEXT;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 146 "idl.ll"
return LOCAL;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 147 "idl.ll"
return INTERFACE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 148 "idl.ll"
return CONST;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 149 "idl.ll"
return TYPEDEF;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 150 "idl.ll"
return STRUCT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 151 "idl.ll"
return ENUM;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 152 "idl.ll"
return STRING;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 153 "idl.ll"
return WSTRING;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 154 "idl.ll"
return SEQUENCE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 155 "idl.ll"
return UNION;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 156 "idl.ll"
return SWITCH;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 157 "idl.ll"
return CASE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 158 "idl.ll"
return DEFAULT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 159 "idl.ll"
return FLOAT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 160 "idl.ll"
return DOUBLE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 161 "idl.ll"
return LONG;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 162 "idl.ll"
return SHORT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 163 "idl.ll"
return UNSIGNED;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 164 "idl.ll"
return CHAR;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 165 "idl.ll"
return WCHAR;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 166 "idl.ll"
return BOOLEAN;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 167 "idl.ll"
return OCTET;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 168 "idl.ll"
return VOID;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 170 "idl.ll"
return CUSTOM;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 171 "idl.ll"
return VALUETYPE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 172 "idl.ll"
return TRUNCATABLE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 173 "idl.ll"
return SUPPORTS;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 174 "idl.ll"
return PUBLIC;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 175 "idl.ll"
return PRIVATE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 176 "idl.ll"
return FACTORY;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 177 "idl.ll"
return ABSTRACT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 179 "idl.ll"
return TRUETOK;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 180 "idl.ll"
return FALSETOK;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 182 "idl.ll"
return INOUT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 183 "idl.ll"
return IN;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 184 "idl.ll"
return OUT;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 185 "idl.ll"
return ONEWAY;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 186 "idl.ll"
return OPAQUE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 188 "idl.ll"
return PFROM;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 190 "idl.ll"
return LEFT_SHIFT;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 191 "idl.ll"
return RIGHT_SHIFT;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 193 "idl.ll"
{
		  yylval.strval = os_strdup ("::");
		  return SCOPE_DELIMITOR;
		}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 199 "idl.ll"
{
    char *z = (char *) os_malloc(strlen(CPPGEN_YYTEXT) + 1);
    os_strcpy(z, CPPGEN_YYTEXT);
    yylval.strval = z;
    return IDENTIFIER;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 206 "idl.ll"
{
							char *z = (char *) os_malloc(strlen(CPPGEN_YYTEXT) + 1);
							strcpy(z, CPPGEN_YYTEXT);
							yylval.strval = z;
							BEGIN NORMAL_STATE;
							return VERSION;
					}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 214 "idl.ll"
{
                  yylval.strval = CPPGEN_YYTEXT;
                  return FLOATING_PT_LITERAL;
                }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 218 "idl.ll"
{
                  yylval.strval = CPPGEN_YYTEXT;
                  return FLOATING_PT_LITERAL;
                }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 223 "idl.ll"
{
		  yylval.ival = idl_atoi(CPPGEN_YYTEXT, 10);
		  return INTEGER_LITERAL;
	        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 227 "idl.ll"
{
		  yylval.ival = idl_atoi(CPPGEN_YYTEXT, 16);
		  return INTEGER_LITERAL;
	        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 231 "idl.ll"
{
		  yylval.ival = idl_atoi(CPPGEN_YYTEXT, 8);
		  return INTEGER_LITERAL;
	      	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 236 "idl.ll"
{
		  CPPGEN_YYTEXT[strlen(CPPGEN_YYTEXT)-1] = '\0';
		  yylval.sval = new UTL_String(CPPGEN_YYTEXT + 1);
		  return STRING_LITERAL;
	      	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 241 "idl.ll"
{
		  yylval.cval = CPPGEN_YYTEXT[1];
		  return CHARACTER_LITERAL;
	      	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 245 "idl.ll"
{
		  // octal character constant
		  yylval.cval = idl_escape_reader(CPPGEN_YYTEXT + 1);
		  return CHARACTER_LITERAL;
		}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "idl.ll"
{
		  yylval.cval = idl_escape_reader(CPPGEN_YYTEXT + 1);
		  return CHARACTER_LITERAL;
		}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 254 "idl.ll"
{/* pragma include */
			BEGIN PRAGMA_STATE;
			return PRAGMA_INCLUDE;
		}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 258 "idl.ll"
{/* pragma async */
			BEGIN PRAGMA_STATE;
			return PRAGMA_ASYNC_CLIENT;
		}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 262 "idl.ll"
{/* pragma async */
			BEGIN PRAGMA_STATE;
			return PRAGMA_ASYNC_SERVER;
		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 266 "idl.ll"
{/* pragma ID */
			return PRAGMA_ID;
		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 269 "idl.ll"
{/* pragma prefix */
			return PRAGMA_PREFIX;
		}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 272 "idl.ll"
{/* pragma version */
			BEGIN PRAGMA_STATE;
			return PRAGMA_VERSION;
		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 276 "idl.ll"
{/* remember pragma */
        /* error! unrecognized pragma */
        return PRAGMA;
		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 280 "idl.ll"
{
            idl_parse_line_and_file(CPPGEN_YYTEXT);
      }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 283 "idl.ll"
{
		  idl_parse_line_and_file(CPPGEN_YYTEXT);
		}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 286 "idl.ll"
{
        idl_parse_line_and_file(CPPGEN_YYTEXT);
      }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 289 "idl.ll"
{
		  idl_parse_line_and_file(CPPGEN_YYTEXT);
		}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 292 "idl.ll"
{
		  idl_parse_line_and_file(CPPGEN_YYTEXT);
	        }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 295 "idl.ll"
{
		  /* ignore cpp ident */
  		  idl_global->set_lineno(idl_global->lineno() + 1);
		}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 299 "idl.ll"
{
		  /* ignore comments */
  		  idl_global->set_lineno(idl_global->lineno() + 1);
		}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 303 "idl.ll"
{
		  for(;;) {
		    char c = yyinput();
		    if (c == '*') {
		      char next = yyinput();
		      if (next == '/')
			break;
		      else
			unput(c);
	              if (c == '\n') 
		        idl_global->set_lineno(idl_global->lineno() + 1);
		    }
	          }
	        }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 317 "idl.ll"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 318 "idl.ll"
{
  		  idl_global->set_lineno(idl_global->lineno() + 1);
			BEGIN NORMAL_STATE;
			return PRAGMA_END;
					}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 323 "idl.ll"
{
  		  idl_global->set_lineno(idl_global->lineno() + 1);
		}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 326 "idl.ll"
return CPPGEN_YYTEXT[0];
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 328 "idl.ll"
ECHO;
	YY_BREAK
#line 1542 "lex_yy.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NORMAL_STATE):
case YY_STATE_EOF(PRAGMA_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 419 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 419 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 418);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 328 "idl.ll"

	/* subroutines */

/*
 * Strip down a name to the last component, i.e. everything after the last
 * '/' character
 */
static char *
stripped_name(UTL_String *fn)
{
    char	*n = fn->get_string();
    long	l;

    if (n == NULL)
	return NULL;
    l = strlen(n);
    for (n += l; l > 0 && *n != '/' && *n != '\\'; l--, n--);
    if (*n == '/' || *n == '\\') n++;
    return n;
}

/*
 * Parse a #line statement generated by the C preprocessor
 */
static void
idl_parse_line_and_file(char *buf)
{
  char		*r = buf;
  char 		*h;
  UTL_String	*nm;

  /* Skip initial '#' */
  if (*r != '#') {
    return;
  }

  /* Find line number */
  for (r++; *r == ' ' || *r == '\t'; r++);
  h = r;
  for (; *r != '\0' && *r != ' ' && *r != '\t'; r++);
  *r++ = 0;
  idl_global->set_lineno(idl_atoi(h, 10));
  
  /* Find file name, if present */
  for (; *r != '"'; r++) {
    if (*r == '\n' || *r == '\0')
      return;
  }
  h = ++r;
  for (; *r != '"'; r++);
  *r = 0;
  if (*h == '\0')
    idl_global->set_filename(new UTL_String("standard input"));
  else
  {
    // figure out whether to include this file...
    UTL_String *new_file = new UTL_String(h);

    idl_global->set_filename(new_file);
    // hide that fact that we are dealing with a temp file
    if(idl_global->filename()->compare(idl_global->real_filename()))
    {
      idl_global->set_filename(idl_global->main_filename());
      idl_global->set_in_main_file(I_TRUE);
    }
    else
    {
      idl_global->set_in_main_file(I_FALSE);
    }
  }

  /*
   * If it's an import file store the stripped name for the BE to use
   */
  if (!(idl_global->in_main_file()) && idl_global->imported() && fstackdepth < 2) {
    nm = new UTL_String(stripped_name(idl_global->filename()));
    idl_global->store_include_file_name(nm);
  }
}
    
/*
 * idl_atoi - Convert a string of digits into an integer according to base b
 */
static long
idl_atoi(char *s, long b)
{
	long	r = 0;
	long	negative = 0;

	if (*s == '-') {
	  negative = 1;
	  s++;
	}
	if (b == 8 && *s == '0')
	  s++;
	else if (b == 16 && *s == '0' && (*(s + 1) == 'x' || *(s + 1) == 'X'))
	  s += 2;

	for (; *s; s++)
	  if (*s <= '9' && *s >= '0')
	    r = (r * b) + (*s - '0');
	  else if (b > 10 && *s <= 'f' && *s >= 'a')
	    r = (r * b) + (*s - 'a' + 10);
	  else if (b > 10 && *s <= 'F' && *s >= 'A')
	    r = (r * b) + (*s - 'A' + 10);
	  else
	    break;

	if (negative)
	  r *= -1;

	return r;
}

/*
 * Convert a string to a float; atof doesn't seem to work, always.
 */
static double
idl_atof(char *s)
{
	double	d = 0.0;
	double	e, k;
	long	neg = 0, negexp = 0;

	if (*s == '-') {
	  neg = 1;
	  s++;
	}
	while (*s >= '0' && *s <= '9') {
		d = (d * 10) + *s - '0';
		s++;
	}
	if (*s == '.') {
		s++;
		e = 10;
		while (*s >= '0' && *s <= '9') {
			d += (*s - '0') / (e * 1.0);
			e *= 10;
			s++;
		}
	}
	if (*s == 'e' || *s == 'E') {
		s++;
		if (*s == '-') {
			negexp = 1;
			s++;
		} else if (*s == '+')
			s++;
		e = 0;
		while (*s >= '0' && *s <= '9') {
			e = (e * 10) + *s - '0';
			s++;
		}
		if (e > 0) {
			for (k = 1; e > 0; k *= 10, e--);
			if (negexp)
				d /= k;
			else
				d *= k;
		}
	}

	if (neg) d *= -1.0;

	return d;
}	

/*
 * Convert (some) escaped characters into their ascii values
 */
static char
idl_escape_reader(
    char *str
)
{
    if (str[0] != '\\') {
	return str[0];
    }

    switch (str[1]) {
      case 'n':
	return '\n';
      case 't':
	return '\t';
      case 'v':
	return '\v';
      case 'b':
	return '\b';
      case 'r':
	return '\r';
      case 'f':
	return '\f';
      case 'a':
	return '\a';
      case '\\':
	return '\\';
      case '\?':
	return '?';
      case '\'':
	return '\'';
      case '"':
	return '"';
      case 'x':
	{
	 int i;
	    // hex value
	    for (i = 2; str[i] != '\0' && isxdigit(str[i]); i++) {
		continue;
	    }
	    char save = str[i];
	    str[i] = '\0';
	    char out = (char)idl_atoi(&str[2], 16);
	    str[i] = save;
	    return out;
	}
	break;
      default:
	// check for octal value
	if (str[1] >= '0' && str[1] <= '7')
	{
	 int i;
	    for (i = 1; str[i] >= '0' && str[i] <= '7'; i++) {
		continue;
	    }
	    char save = str[i];
	    str[i] = '\0';
	    char out = (char)idl_atoi(&str[1], 8);
	    str[i] = save;
	    return out;
	} else {
	  return str[1] - 'a';
	}
	break;
    }
}
