/*
 *                         OpenSplice DDS
 *
 *   This software and documentation are Copyright 2006 to 2013 PrismTech
 *   Limited and its licensees. All rights reserved. See file:
 *
 *                     $OSPL_HOME/LICENSE 
 *
 *   for full copyright notice and license terms. 
 *
 */

/************************************************************************
 * LOGICAL_NAME:    WhiteListObjects.idl
 * FUNCTION:        OpenSplice Tutorial example code.
 * MODULE:          Tutorial for the Java programming language.
 * DATE             june 2008.
 ************************************************************************
 *
 * This file contains the object definitions for the DLRL tutorial examples.
 *
 ***/

#include "dds_dlrl.idl"

module DLRLChat
{

    valuetype User;                // Object representing a Chatroom User.
    valuetype UserSet;             // Object representing a Set<User>.
    valuetype ChatMessage;         // Object representing a Chat message.
    valuetype WhiteList;           // Object representing a named whitelist.

    valuetype ChatMessage : DDS::ObjectRoot
    {
        public long id;
        public long index;
        public string message;
        public User sender;

        void display();
    };

    valuetype User : DDS::ObjectRoot
    {
        public long id;
        public string name;
        public ChatMessage lastMsg;
    };

    valuetype WhiteList : DDS::ObjectRoot
    {
        public string name;             // name of the WhiteList
        public UserSet friends;         // Collection of Users that make up the WhiteList.

        void addUser(in User a_user);   // Operation to add a user.
    };
};
