
#ifndef OS_COMMON_SIGNAL_H
#define OS_COMMON_SIGNAL_H

#include <signal.h>

#define OS_SIGTERM	SIGTERM
#define OS_SIGINT	SIGINT
#define OS_SIGHUP	SIGHUP
#define OS_SIGKILL	SIGKILL
#define OS_SIGPIPE	SIGPIPE
#define OS_SIGALRM	SIGALRM
#define OS_SIGUSR1	SIGUSR1
#define OS_SIGUSR2	SIGUSR2
#define OS_SIGPOLL	SIGPOLL
#define OS_SIGVTALRM	SIGVTALRM
#define OS_SIGPROF	SIGPROF

#endif /* OS_COMMON_SIGNAL_H */
