/**
 * This file defines the type for the Shape Demo -- the application
 * currently used to demonstrate interoperability between DDS vendors.
 *
 * Notice that the key is currently expressed using the X-Types
 * syntax. If you don't support X-Types yet just add your own
 * annotation to let the "color" attribute be the key of the ShapeType
 * topic type.
 *
 */
struct ShapeType {
    string color; //@Key
    long x;
    long y;
    long shapesize;
};
#pragma keylist ShapeType color
