/**
 * @addtogroup examplesdcpsThroughputisocpp
 */
/** @{*/
/** @file */

module ThroughputModule
{
    struct DataType
    {
        unsigned long long count;
        sequence<octet> payload;
    };
    #pragma stream DataType
    #pragma keylist DataType
};

/** @}*/
