
 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensplice_dds_dcps_FooDataWriterImpl */

#ifndef _Included_org_opensplice_dds_dcps_FooDataWriterImpl
#define _Included_org_opensplice_dds_dcps_FooDataWriterImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniRegisterInstance
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniRegisterInstance
  (JNIEnv *, jclass, jobject, jlong, jobject);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniRegisterInstanceWTimestamp
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;LDDS/Time_t;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniRegisterInstanceWTimestamp
  (JNIEnv *, jclass, jobject, jlong, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniUnregisterInstance
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniUnregisterInstance
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniUnregisterInstanceWTimestamp
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;JLDDS/Time_t;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniUnregisterInstanceWTimestamp
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniWrite
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniWrite
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniWriteWTimestamp
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;JLDDS/Time_t;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniWriteWTimestamp
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniDispose
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniDispose
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniDisposeWTimestamp
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;JLDDS/Time_t;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniDisposeWTimestamp
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniWritedispose
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniWritedispose
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniWritedisposeWTimestamp
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;JLDDS/Time_t;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniWritedisposeWTimestamp
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniGetKeyValue
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniGetKeyValue
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

/*
 * Class:     org_opensplice_dds_dcps_FooDataWriterImpl
 * Method:    jniLookupInstance
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensplice_dds_dcps_FooDataWriterImpl_jniLookupInstance
  (JNIEnv *, jclass, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
