
 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensplice_dds_dcps_PublisherImpl */

#ifndef _Included_org_opensplice_dds_dcps_PublisherImpl
#define _Included_org_opensplice_dds_dcps_PublisherImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniCreateDatawriter
 * Signature: (LDDS/Topic;LDDS/DataWriterQos;LDDS/DataWriterListener;I)LDDS/DataWriter;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniCreateDatawriter
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniDeleteDatawriter
 * Signature: (LDDS/DataWriter;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniDeleteDatawriter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniLookupDatawriter
 * Signature: (Ljava/lang/String;)LDDS/DataWriter;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniLookupDatawriter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniDeleteContainedEntities
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniDeleteContainedEntities
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniSetQos
 * Signature: (LDDS/PublisherQos;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniSetQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniGetQos
 * Signature: (LDDS/PublisherQosHolder;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniGetQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniSetListener
 * Signature: (LDDS/PublisherListener;I)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniSetListener
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniGetListener
 * Signature: ()LDDS/PublisherListener;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniGetListener
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniSuspendPublications
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniSuspendPublications
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniResumePublications
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniResumePublications
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniBeginCoherentChanges
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniBeginCoherentChanges
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniEndCoherentChanges
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniEndCoherentChanges
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniWaitForAcknowledgments
 * Signature: (LDDS/Duration_t;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniWaitForAcknowledgments
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniGetParticipant
 * Signature: ()LDDS/DomainParticipant;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniGetParticipant
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniSetDefaultDatawriterQos
 * Signature: (LDDS/DataWriterQos;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniSetDefaultDatawriterQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniGetDefaultDatawriterQos
 * Signature: (LDDS/DataWriterQosHolder;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniGetDefaultDatawriterQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_PublisherImpl
 * Method:    jniCopyFromTopicQos
 * Signature: (LDDS/DataWriterQosHolder;LDDS/TopicQos;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_PublisherImpl_jniCopyFromTopicQos
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
