/*
 *                         OpenSplice DDS
 *
 *   This software and documentation are Copyright 2006 to 2009 PrismTech 
 *   Limited and its licensees. All rights reserved. See file:
 *
 *                     $OSPL_HOME/LICENSE 
 *
 *   for full copyright notice and license terms. 
 *
 */

 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensplice_dds_dcps_ReadConditionImpl */

#ifndef _Included_org_opensplice_dds_dcps_ReadConditionImpl
#define _Included_org_opensplice_dds_dcps_ReadConditionImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensplice_dds_dcps_ReadConditionImpl
 * Method:    jniGetSampleStateMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_ReadConditionImpl_jniGetSampleStateMask
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_ReadConditionImpl
 * Method:    jniGetViewStateMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_ReadConditionImpl_jniGetViewStateMask
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_ReadConditionImpl
 * Method:    jniGetInstanceStateMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_ReadConditionImpl_jniGetInstanceStateMask
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_ReadConditionImpl
 * Method:    jniGetDatareader
 * Signature: ()LDDS/DataReader;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_ReadConditionImpl_jniGetDatareader
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
