/*
 *                         OpenSplice DDS
 *
 *   This software and documentation are Copyright 2006 to 2009 PrismTech 
 *   Limited and its licensees. All rights reserved. See file:
 *
 *                     $OSPL_HOME/LICENSE 
 *
 *   for full copyright notice and license terms. 
 *
 */

 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensplice_dds_dcps_SubscriberImpl */

#ifndef _Included_org_opensplice_dds_dcps_SubscriberImpl
#define _Included_org_opensplice_dds_dcps_SubscriberImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniCreateDatareader
 * Signature: (LDDS/TopicDescription;LDDS/DataReaderQos;LDDS/DataReaderListener;I)LDDS/DataReader;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniCreateDatareader
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniDeleteDatareader
 * Signature: (LDDS/DataReader;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniDeleteDatareader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniDeleteContainedEntities
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniDeleteContainedEntities
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniLookupDatareader
 * Signature: (Ljava/lang/String;)LDDS/DataReader;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniLookupDatareader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniGetDatareaders
 * Signature: (LDDS/DataReaderSeqHolder;III)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniGetDatareaders
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniNotifyDatareaders
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniNotifyDatareaders
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniSetQos
 * Signature: (LDDS/SubscriberQos;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniSetQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniGetQos
 * Signature: (LDDS/SubscriberQosHolder;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniGetQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniSetListener
 * Signature: (LDDS/SubscriberListener;I)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniSetListener
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniGetListener
 * Signature: ()LDDS/SubscriberListener;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniGetListener
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniBeginAccess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniBeginAccess
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniEndAccess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniEndAccess
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniGetParticipant
 * Signature: ()LDDS/DomainParticipant;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniGetParticipant
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniSetDefaultDatareaderQos
 * Signature: (LDDS/DataReaderQos;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniSetDefaultDatareaderQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniGetDefaultDatareaderQos
 * Signature: (LDDS/DataReaderQosHolder;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniGetDefaultDatareaderQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_SubscriberImpl
 * Method:    jniCopyFromTopicQos
 * Signature: (LDDS/DataReaderQosHolder;LDDS/TopicQos;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_SubscriberImpl_jniCopyFromTopicQos
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
