
 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensplice_dds_dcps_TypeSupportImpl */

#ifndef _Included_org_opensplice_dds_dcps_TypeSupportImpl
#define _Included_org_opensplice_dds_dcps_TypeSupportImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensplice_dds_dcps_TypeSupportImpl
 * Method:    jniGetTypeName
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensplice_dds_dcps_TypeSupportImpl_jniGetTypeName
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
