
 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensplice_dds_dcps_DomainImpl */

#ifndef _Included_org_opensplice_dds_dcps_DomainImpl
#define _Included_org_opensplice_dds_dcps_DomainImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensplice_dds_dcps_DomainImpl
 * Method:    jniCreatePersistentSnapshot
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_DomainImpl_jniCreatePersistentSnapshot
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
