
 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensplice_dds_dcps_DataReaderViewImpl */

#ifndef _Included_org_opensplice_dds_dcps_DataReaderViewImpl
#define _Included_org_opensplice_dds_dcps_DataReaderViewImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniCreateReadcondition
 * Signature: (III)LDDS/ReadCondition;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniCreateReadcondition
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniCreateQuerycondition
 * Signature: (IIILjava/lang/String;[Ljava/lang/String;)LDDS/QueryCondition;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniCreateQuerycondition
  (JNIEnv *, jobject, jint, jint, jint, jstring, jobjectArray);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniDeleteReadcondition
 * Signature: (LDDS/ReadCondition;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniDeleteReadcondition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniDeleteContainedEntities
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniDeleteContainedEntities
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniSetQos
 * Signature: (LDDS/DataReaderViewQos;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniSetQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniGetQos
 * Signature: (LDDS/DataReaderViewQosHolder;)I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniGetQos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniGetDataReader
 * Signature: ()LDDS/DataReader;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniGetDataReader
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniGetStatusCondition
 * Signature: ()LDDS/StatusCondition;
 */
JNIEXPORT jobject JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniGetStatusCondition
  (JNIEnv *, jobject);

/*
 * Class:     org_opensplice_dds_dcps_DataReaderViewImpl
 * Method:    jniGetStatusChanges
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensplice_dds_dcps_DataReaderViewImpl_jniGetStatusChanges
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
