// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v%DOTNET%", FrameworkDisplayName = ".NET Framework v%DOTNET%")]
