#ifndef OSPL_DDS_DCPS_BUILTINTOPICS_IDL
#define OSPL_DDS_DCPS_BUILTINTOPICS_IDL

/**
*This file (name) was orginally in ./src/api/dcps/ccpp/idl/.
*It's been modified to include from another file the base definitions
*required for this 'built in topics' superset... :
*/

#include "dds_builtinTopics.idl"

module DDS {

    struct Time_t {
        long sec;
        unsigned long nanosec;
    };

    struct EntityFactoryQosPolicy {
        boolean autoenable_created_entities;
    };

    struct WriterDataLifecycleQosPolicy {
        boolean autodispose_unregistered_instances;
        Duration_t autopurge_suspended_samples_delay;
        Duration_t autounregister_instance_delay;
    };

    struct ReaderDataLifecycleQosPolicy {
        Duration_t autopurge_nowriter_samples_delay;
        Duration_t autopurge_disposed_samples_delay;
        // @discrepancy The below member existed in this file but did not
        // in ./etc/idlpp/dds_dcps.idl. Retain ?
        boolean enable_invalid_samples;
    };

// @discrepancy The below 3 QoS did not exist in ./etc/idlpp/dds_dcps.idl Retain ?

    struct SubscriptionKeyQosPolicy {
        boolean use_key_list;
        StringSeq key_list;
    };

    struct ReaderLifespanQosPolicy {
        boolean use_lifespan;
        Duration_t duration;
    };

    struct ShareQosPolicy {
        string name;
        boolean enable;
    };

// @discrepancy End of above discrepancy

    enum SchedulingClassQosPolicyKind {
        SCHEDULE_DEFAULT,
        SCHEDULE_TIMESHARING,
        SCHEDULE_REALTIME
    };

    struct SchedulingClassQosPolicy {
        SchedulingClassQosPolicyKind kind;
    };

    enum SchedulingPriorityQosPolicyKind {
        PRIORITY_RELATIVE,
        PRIORITY_ABSOLUTE
    };

    struct SchedulingPriorityQosPolicy {
        SchedulingPriorityQosPolicyKind kind;
    };

    struct SchedulingQosPolicy {
        SchedulingClassQosPolicy scheduling_class;
        SchedulingPriorityQosPolicy scheduling_priority_kind;
        long scheduling_priority;
    };

    struct ViewKeyQosPolicy {
        boolean use_key_list;
        StringSeq key_list;
    };

    struct DataReaderViewQos {
        ViewKeyQosPolicy view_keys;
    };

    struct DomainParticipantFactoryQos {
        EntityFactoryQosPolicy entity_factory;
    };

    struct DomainParticipantQos {
        UserDataQosPolicy user_data;
        EntityFactoryQosPolicy entity_factory;
        SchedulingQosPolicy watchdog_scheduling;
        SchedulingQosPolicy listener_scheduling;
    };

    struct TopicQos {
        TopicDataQosPolicy topic_data;
        DurabilityQosPolicy durability;
        DurabilityServiceQosPolicy durability_service;
        DeadlineQosPolicy deadline;
        LatencyBudgetQosPolicy latency_budget;
        LivelinessQosPolicy liveliness;
        ReliabilityQosPolicy reliability;
        DestinationOrderQosPolicy destination_order;
        HistoryQosPolicy history;
        ResourceLimitsQosPolicy resource_limits;
        TransportPriorityQosPolicy transport_priority;
        LifespanQosPolicy lifespan;
        OwnershipQosPolicy ownership;
    };

    struct DataWriterQos {
        DurabilityQosPolicy durability;
        DeadlineQosPolicy deadline;
        LatencyBudgetQosPolicy latency_budget;
        LivelinessQosPolicy liveliness;
        ReliabilityQosPolicy reliability;
        DestinationOrderQosPolicy destination_order;
        HistoryQosPolicy history;
        ResourceLimitsQosPolicy resource_limits;
        TransportPriorityQosPolicy transport_priority;
        LifespanQosPolicy lifespan;
        UserDataQosPolicy user_data;
        // @discrepancy The below 'ownership' member was not present in ./etc/idlpp/dds_dcps.idl
        OwnershipQosPolicy ownership;
        OwnershipStrengthQosPolicy ownership_strength;
        WriterDataLifecycleQosPolicy writer_data_lifecycle;
    };

    struct PublisherQos {
        PresentationQosPolicy presentation;
        PartitionQosPolicy partition;
        GroupDataQosPolicy group_data;
        EntityFactoryQosPolicy entity_factory;
    };

    struct DataReaderQos {
        DurabilityQosPolicy durability;
        DeadlineQosPolicy deadline;
        LatencyBudgetQosPolicy latency_budget;
        LivelinessQosPolicy liveliness;
        ReliabilityQosPolicy reliability;
        DestinationOrderQosPolicy destination_order;
        HistoryQosPolicy history;
        ResourceLimitsQosPolicy resource_limits;
        UserDataQosPolicy user_data;
        // @discrepancy The below 'ownership' member was not present in ./etc/idlpp/dds_dcps.idl
        OwnershipQosPolicy ownership;
        TimeBasedFilterQosPolicy time_based_filter;
        ReaderDataLifecycleQosPolicy reader_data_lifecycle;
        // @discrepancy The below 'subscription_keys' member was not present in ./etc/idlpp/dds_dcps.idl
        SubscriptionKeyQosPolicy subscription_keys;
        // @discrepancy The below 'reader_lifespan' member was not present in ./etc/idlpp/dds_dcps.idl
        ReaderLifespanQosPolicy reader_lifespan;
        // @discrepancy The below 'share' member was not present in ./etc/idlpp/dds_dcps.idl
        ShareQosPolicy share;
    };

    struct SubscriberQos {
        PresentationQosPolicy presentation;
        PartitionQosPolicy partition;
        GroupDataQosPolicy group_data;
        EntityFactoryQosPolicy entity_factory;
        ShareQosPolicy share;
    };

};

#endif /* DDS_DCPS_BUILTINTOPICS_IDL */
