#
export DCPS_PATH=$PWD

#SUBSYSTEMS	:= C++
#SUBSYSTEMS	+= C
#SUBSYSTEMS	+= Java
#SUBSYSTEMS      += ContentFilteredTopic
#SUBSYSTEMS      += Durability
#SUBSYSTEMS      += HelloWorld
#SUBSYSTEMS      += Lifecycle
#SUBSYSTEMS      += Listener
#SUBSYSTEMS      += Ownership
#SUBSYSTEMS      += QueryCondition
#SUBSYSTEMS      += WaitSet


include $(OSPL_HOME)/setup/makefiles/subsystem.mak
