/**
 * @addtogroup examplesdcpsHelloWorldisocpp
 */
/** @{*/
/** @file */

module PingPongData
{
   struct Msg
   {
      /** User ID */
      long userID;
      /**  message */
      string message;
   };
   #pragma keylist Msg userID
};

/** @}*/
