// $Id$

module TestModule
{

    //typedef sequence<long, 1> long1Seq;
    //typedef sequence<long1Seq > long2Seq[1];

    struct Hello
    {
        string the_message;
        //long1Seq foo;
        //long2Seq bar;
    };

    #pragma keylist Hello the_message
};
