/** \file 
 * \brief File that defines data structure for the test.
 * 
 */

module dds2734 {

    /** \brief Struct of data for the test
    */
    struct TestTopic {
        /** TestTopic identifier
        */
        long      id;          
    };
#pragma keylist TestTopic id

};
