.PHONY: all all_no_installer
all:
	./make_all

all_no_installer:
	./make_all -noinstaller

clean:
#(cd service_installer; make clean)
	@rm -rf HDE RTS VC
	@rm -f x86.linux2.6*.xml
	@rm -f x86.win32*.xml

