#!/bin/bash
#
# Make RTS mirror
#
. ${OSPL_HOME}/install/make_functions

echo "* Build SPLICE RTS"

set_rts_envs "$@"
remove_rts_mirror
create_rts_mirror

echo "*   Prepare RTS for target ${RTS_subdir}"
install_rts_target
echo "*   RTS prepared for target ${RTS_subdir} Ready"

echo "* SPLICE RTS Ready"
