#!/bin/bash

. $OSPL_HOME/install/make_functions

set_envs "$@"

make_hde_mirror_and_builder

if [ "${SOURCE_TARGET_SHORT}" != "int" -a "${SOURCE_TARGET_SHORT}" != "pikeos" ]
then
    make_rts_mirror_and_builder
fi

if [ "${OSPL_QT_IS_ON}" == "yes" ]
then
    make_demos_mirror_and_builder
fi

if [ "${INCLUDE_STE}" == "yes" ]
then
    make_ste_mirror_and_builder
fi
