#!/bin/bash

. ${OSPL_HOME}/install/make_functions

echo "make_builder params are $@"

installer_setup "$@"

OSPL_BUILDER_APP=`echo $OSPL_BUILDER | awk -F'/' '{ print $NF }'`

if [ -z "$SPLICE_HOST_FULL" ]
then
    echo "*** Warning: SPLICE_HOST_FULL unset, using SPLICE_HOST ($SPLICE_HOST)"
    SPLICE_HOST_FULL=$SPLICE_HOST
fi
INSTALLER_FILENAME=OpenSpliceDDS${PACKAGE_VERSION}-${INSTTYPE}-${SPLICE_HOST_FULL}${EXTRA}

if [ "${OSPL_BUILDER_APP}" != "builder" ]
then
    set_hde_envs "${SOURCE_TARGET}" "${SOURCE_HOST}" "${PACKAGE_VERSION}" "${PACKAGE_DATE}" \
            "${ENV}" "${TXTFILE_CONVERTER}" "${SOURCE_HOST_SHORT}" "${SOURCE_TARGET_SHORT}"
    doStandardPackage
fi
