#!/bin/bash

#
# Make HDE mirror
#

. ${OSPL_HOME}/install/make_functions

echo "* Build SPLICE HDE"

set_hde_envs "$@"
remove_hde_mirror
create_hde_mirror

echo "*   Prepare HDE for target ${HDE_subdir}"
install_hde_target
if [ $? == 0 ]
then
    echo "*   HDE prepared for target ${HDE_subdir} Ready"
else
    echo "*   Error building HDE."
    exit 1
fi

if [ -z "$OSPL_OUTER_HOME" ]
then
    echo "* SPLICE HDE Ready"
fi
