#!/bin/bash
#
# Make RTS mirror
#
. ${OSPL_HOME}/install/make_functions

echo "* Build SPLICE RTS"

set_rts_envs $*
remove_rts_mirror
create_rts_mirror

echo "*   Prepare RTS for target ${RTS_subdir}"
install_rts_target "${RTS_dir}" "${target}" "${target_version}" "${target_date}" "${suffix_exe}" "${suffix_script}" "${source_env}" "${target_env}"
echo "*   RTS prepared for target ${RTS_subdir} Ready"

echo "* SPLICE RTS Ready"
