#! /bin/sh
args=
while [ $# -gt 0 ]
do
args="$args $1 "
shift
done

java -classpath bld:bld/WhiteListEditor:$OSPL_HOME/jar/dcpssaj.jar:$OSPL_HOME/jar/dlrlsaj.jar WhiteListEditor.WhiteListEditor $args
