ifeq ($(INCLUDE_FILTERS),yes)
link:
	(cd filters; make compile)

compile:
	(cd filters; make compile)

clean:
	(cd filters; make clean)

qac:

gcov:

analyse:

else # INCLUDE_FILTERS=no

link:
compile:
clean:
qac:
gcov:

endif
