/*
 *                         OpenSplice DDS
 *
 *   This software and documentation are Copyright 2006 to 2013 PrismTech
 *   Limited and its licensees. All rights reserved. See file:
 *
 *                     $OSPL_HOME/LICENSE 
 *
 *   for full copyright notice and license terms. 
 *
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DDS_Set */

#ifndef _Included_DDS_Set
#define _Included_DDS_Set
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DDS_Set
 * Method:    jniAdd
 * Signature: (LDDS/ObjectRoot;)V
 */
JNIEXPORT void JNICALL Java_DDS_Set_jniAdd
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniRemove
 * Signature: (LDDS/ObjectRoot;)V
 */
JNIEXPORT void JNICALL Java_DDS_Set_jniRemove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniContains
 * Signature: (LDDS/ObjectRoot;)Z
 */
JNIEXPORT jboolean JNICALL Java_DDS_Set_jniContains
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DDS_Set_jniLength
  (JNIEnv *, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DDS_Set_jniClear
  (JNIEnv *, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniDeleteSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DDS_Set_jniDeleteSet
  (JNIEnv *, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniAddedElements
 * Signature: ()[LDDS/ObjectRoot;
 */
JNIEXPORT jobjectArray JNICALL Java_DDS_Set_jniAddedElements
  (JNIEnv *, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniRemovedElements
 * Signature: ()[LDDS/ObjectRoot;
 */
JNIEXPORT jobjectArray JNICALL Java_DDS_Set_jniRemovedElements
  (JNIEnv *, jobject);

/*
 * Class:     DDS_Set
 * Method:    jniGetValues
 * Signature: ()[LDDS/ObjectRoot;
 */
JNIEXPORT jobjectArray JNICALL Java_DDS_Set_jniGetValues
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
